import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/themefour/layout/NavBar";
import Footer from "@/components/themefour/layout/Footer";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Theme 4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable} ${montserrat.variable}`}>
      <body>
        <NavBar />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
